const {test}=require('node:test'),assert=require('node:assert/strict');
const {Engine,intentOf,collectArtists,hasArtist,mixUris,commentary,Narrator,transitionFit,NativeTransitions,migrateProfile}=require('../poor-mans-dj.js');
const artist={uri:'spotify:artist:0000000000000000000001',name:'Target'};
const t=(id,target=true)=>({uri:'spotify:track:'+String(id).padStart(22,'0'),uid:'u'+id,name:'Track '+id,artists:[target?artist:{uri:'spotify:artist:0000000000000000000002',name:'Related'}],affinity:true,source:target?'artista actual':'artista relacionado',duration:200000});
function fixture(){let q=[],savedMix,serial=0;const pool=[...Array.from({length:30},(_,i)=>t(i+2)),...Array.from({length:15},(_,i)=>t(i+100,false))];const io={queue:()=>({all:q,priority:q}),save:()=>{},search:async()=>({tracks:[],artists:[artist]}),artistTracks:async()=>pool.filter(x=>hasArtist(x,artist)),candidates:async()=>pool,play:async()=>{},add:async tracks=>{const added=tracks.map(t=>({...t,uid:'dj'+serial++}));q.push(...added);return added;},remove:async tracks=>q=q.filter(t=>!tracks.some(x=>x.uid===t.uid)),createMix:async(a,mode,tracks)=>{savedMix={mode,tracks};return {uri:'spotify:playlist:0000000000000000000001',name:'Mix',count:tracks.length};}};const e=new Engine(io);e.trackChanged(t(1));return {e,pool,saved:()=>savedMix};}
test('artist-only search result has a menu even without any track results',async()=>{const f=fixture();await f.e.command('Target');assert.equal(f.e.commandChoices.length,0);assert.equal(f.e.commandArtists.length,1);await f.e.chooseArtist(artist.uri);assert.equal(f.e.active,false);assert.equal(f.e.artistMenu.uri,artist.uri);});
test('artist-only mode queues and saves only credited tracks of the artist',async()=>{const f=fixture();await f.e.command('Target');await f.e.chooseArtist(artist.uri,'only');assert.equal(f.e.active,true);assert.equal(f.e.intent.artistMode,'only');assert.equal(f.e.eligible(t(100,false)),false);assert.ok(f.saved().tracks.length>15);assert.ok(f.saved().tracks.every(x=>hasArtist(x,artist)));await f.e.stop();});
test('random artist mode has roughly three target songs per related song in its saved mix',async()=>{const f=fixture();await f.e.command('Target');await f.e.chooseArtist(artist.uri,'mix');const plan=f.saved().tracks,ratio=plan.filter(t=>hasArtist(t,artist)).length/plan.length;assert.equal(plan.length,24);assert.ok(ratio>=.7 && ratio<=.85,ratio);assert.equal(new Set(plan.map(t=>t.uri)).size,plan.length);await f.e.stop();});
test('artist-only includes credited collaborations but excludes other artists',()=>{const f=fixture();f.e.intent=intentOf({artist,artistMode:'only',known:false});assert.equal(f.e.eligible({...t(2),artists:[...t(100,false).artists,artist]}),true);assert.equal(f.e.eligible(t(100,false)),false);});
test('artist extraction keeps names and images from actual artist entities',()=>{const artists=collectArtists({items:[{data:{uri:artist.uri,profile:{name:artist.name},visuals:{avatarImage:{sources:[{url:'cover'}]}}}}]});assert.equal(artists.length,1);assert.equal(artists[0].image,'cover');});
test('narration has broad variation, stays short, and does not infer an undeclared genre',()=>{const texts=new Set();for(let i=0;i<120;i++){const s=commentary('start',t(1),intentOf({known:false}),i);assert.ok(s.split(/\s+/).length<=25);assert.ok(!s.includes('alabanzas'));texts.add(s);}assert.ok(texts.size>=70,texts.size);});
test('twenty successive captions do not repeat even with the same reference',()=>{const n=new Narrator({}),texts=[];for(let i=0;i<20;i++){n.say('direction',t(1),intentOf());texts.push(n.text);}assert.equal(new Set(texts).size,20);n.dispose();});
test('transition ranking prefers compatible tempo, key and loudness without fabricating missing data',()=>{const from={bpm:120,key:0,mode:1,loudness:-8},smooth=transitionFit(from,{bpm:121,key:0,mode:1,loudness:-9}),abrupt=transitionFit(from,{bpm:157,key:6,mode:0,loudness:-2});assert.ok(smooth.value>abrupt.value);assert.equal(transitionFit(null,null).value,null);});
test('native transition controls are explicit and restore the previous values',async()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},setting=v=>({value:v,setValue:async function(n){this.value=n;}}),playback={audioCrossfade:setting(false),audioCrossfadeMs:setting(5000),gapless:setting(true)},native=new NativeTransitions({SettingsAPI:{playback}},storage,()=>true);assert.equal(native.state().enabled,false);await native.apply(4);assert.equal(playback.audioCrossfade.value,true);assert.equal(playback.audioCrossfadeMs.value,4000);await native.restore();assert.equal(playback.audioCrossfade.value,false);assert.equal(playback.audioCrossfadeMs.value,5000);});
test('retrying a partial playlist keeps its original plan instead of appending a newly random plan',()=>{const original=[t(1).uri,t(2).uri],pending={key:'artist:only',tracks:original};assert.deepEqual(mixUris(pending,'artist:only',[t(3),t(4)]),original);assert.deepEqual(mixUris(pending,'artist:mix',[t(3),t(4)]),[t(3).uri,t(4).uri]);});
test('saved playlist link survives profile migration without accepting an arbitrary URL',()=>{const mix={uri:'spotify:playlist:0000000000000000000001',name:'My mix',count:24};assert.deepEqual(migrateProfile({schema:3,mixPlaylist:mix}).mixPlaylist,mix);assert.equal(migrateProfile({schema:3,mixPlaylist:{...mix,uri:'https://example.com'}}).mixPlaylist,null);});
test('identical display names cannot substitute a different Spotify artist identity',()=>{assert.equal(hasArtist({...t(2),artists:[{...artist,uri:'spotify:artist:0000000000000000000009'}]},artist),false);});
