const {test}=require('node:test'),assert=require('node:assert/strict');
const {Engine,compatibility}=require('../poor-mans-dj.js');
const t=(i,bpm=120)=>({uri:'spotify:track:'+String(i).padStart(22,'0'),uid:'u'+i,name:'T'+i,artists:[{name:'Artist '+i}],duration:200000,affinity:true,familiar:true,playlist:true,audio:{bpm,key:0,mode:1}});
function fixture(){let q=[],serial=0,removed=[];const io={queue:()=>({priority:q.slice(),all:q.slice()}),candidates:async()=>[t(2),t(3),t(4),t(5)],enrich:async()=>{},save:()=>{},add:async ts=>{const rows=ts.map(x=>({...x,uid:'dj'+serial++}));q.push(...rows);return rows;},remove:async ts=>{removed.push(...ts);q=q.filter(x=>!ts.some(y=>y.uid===x.uid));}};const e=new Engine(io,{},()=>0);e.trackChanged(t(1));return {e,io,q:()=>q,set:rows=>q=rows,removed};}
test('manual queue addition takes precedence and removes all DJ suggestions',async()=>{const f=fixture();await f.e.start();assert.equal(f.q().length,1);const own=f.q()[0];f.set([own,t(90)]);await f.e.reconcileManual();assert.deepEqual(f.q().map(x=>x.uid),['u90']);assert.equal(f.e.active,false);assert.equal(f.e.anchor.uri,t(90).uri);});
test('manual choice is honored without waiting for acoustic analysis',async()=>{const f=fixture();await f.e.start();f.io.enrich=()=>{throw Error('must not analyze');};f.set([...f.q(),{...t(90),audio:null}]);await f.e.reconcileManual();assert.deepEqual(f.q().map(x=>x.uri),[t(90).uri]);assert.equal(f.e.error,false);});
test('manual choice overrides even a reserved suggestion',async()=>{const f=fixture();await f.e.start();f.e.reserve(f.e.preview[0]);f.set([...f.q(),t(90)]);await f.e.reconcileManual();assert.deepEqual(f.q().map(x=>x.uid),['u90']);});
test('stop after manual takeover restores a suspended queue without deleting new choices',async()=>{const f=fixture();f.e.settings.takeover=true;f.set([t(99)]);await f.e.start();f.set([t(90),...f.q()]);await f.e.reconcileManual();await f.e.stop();assert.deepEqual(f.q().map(x=>x.uri),[t(90).uri,t(99).uri]);assert.equal(f.e.captured,false);});
test('preexisting manual queue is retained by default without inserting ahead',async()=>{const f=fixture();f.set([t(99)]);await f.e.start();await f.e.reconcileManual();assert.deepEqual(f.q().map(x=>x.uid),['u99']);assert.equal(f.e.active,true);assert.equal(f.e.captured,false);});
test('direct manual playback moves anchor without punishing previous song',async()=>{const f=fixture();await f.e.start();f.e.observedMs=4000;f.e.trackChanged(t(90));if(f.e.flight)await f.e.flight;assert.equal(f.e.anchor.uri,t(90).uri);assert.equal(f.e.memory[t(1).uri],undefined);});
test('expected transition keeps cancellation under playback control',()=>{const f=fixture();f.e.active=true;let cancelled=0;f.io.cancelTransition=()=>cancelled++;f.e.trackChanged(t(90),true);assert.equal(cancelled,0);assert.equal(f.e.anchor.uri,t(90).uri);});
test('manual duplicate of DJ URI retains its distinct UID on stop',async()=>{const f=fixture();await f.e.start();const duplicate={...f.q()[0],uid:'manual-copy'};f.set([duplicate,...f.q()]);await f.e.reconcileManual();await f.e.stop();assert.deepEqual(f.q().map(x=>x.uid),['manual-copy']);});
