const {test}=require('node:test'),assert=require('node:assert/strict');
const {Engine,normalize,migrateProfile,ChoiceDeck,Narrator,VoiceGate,intentOf}=require('../poor-mans-dj.js');
const t=i=>({uri:'spotify:track:'+String(i).padStart(22,'0'),name:'Track '+i,artists:[{name:'Example'}],image:'https://i.scdn.co/image/cover'+i,album:'Album',duration:200000,playlist:true,evidence:['playlist']});
test('saved covers and album survive schema 3 migration and normalization',()=>{const track=t(1);assert.equal(normalize(track).image,track.image);assert.equal(normalize(track).album,'Album');assert.equal(migrateProfile({schema:3,memory:{[track.uri]:{track,heard:1}}}).memory[track.uri].track.image,track.image);});
test('history with missing cover cannot overwrite the current playlist artwork',()=>{const track=t(1),e=new Engine({queue:()=>({all:[track],priority:[]}),save:()=>{}},{schema:3,memory:{[track.uri]:{heard:1,track:{...track,image:''}}}});assert.equal(e.knownTracks()[0].image,track.image);});
test('reopening the same known pool continues the cycle rather than repeating its first pair',()=>{const d=new ChoiceDeck(()=>.4),pool=[1,2,3,4,5,6].map(t),first=d.set(pool).map(x=>x.uri),next=d.set(pool).map(x=>x.uri);assert.ok(next.every(uri=>!first.includes(uri)));d.next();assert.deepEqual(d.set(pool),[]);assert.equal(d.reset().length,2);});
test('late cover results update visible cards but not a superseded pair',async()=>{let done;const e=new Engine({queue:()=>({all:[{...t(1),image:''},{...t(2),image:''},t(3),t(4)],priority:[]}),save:()=>{},cardDetails:track=>new Promise(r=>done=()=>r({...track,image:'cover'}))});e.prepareChoices();const pair=e.deck.pair;e.nextChoices();done?.();await new Promise(r=>setImmediate(r));assert.notEqual(e.deck.pair,pair);});
function fixture(available=true){let playing=true,uri='one',device='local',pauses=0,resumes=0,gate;const utterances=[];const host={speechSynthesis:{getVoices:()=>available?[{name:'Sabina',lang:'es-MX',localService:true}]:[],addEventListener:()=>{},removeEventListener:()=>{},cancel:()=>{},speak:u=>{assert.equal(playing,false);utterances.push(u);}},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};const n=new Narrator(host);const music={playing:()=>playing,uri:()=>uri,device:()=>device,pause:()=>{pauses++;playing=false;gate.playbackChanged();},resume:()=>{resumes++;playing=true;gate.playbackChanged();}};gate=new VoiceGate(n,music);return {n,gate,utterances,stats:()=>({playing,pauses,resumes}),setUri:value=>uri=value,setDevice:value=>device=value};}
test('music is paused before speech and resumes exactly once only after onend',async()=>{const f=fixture(),p=f.gate.run('start',t(1),intentOf());await Promise.resolve();assert.equal(f.stats().pauses,1);assert.equal(f.stats().resumes,0);assert.equal(f.n.speaking,true);f.utterances[0].onend();await p;assert.equal(f.stats().resumes,1);f.n.dispose();});
test('unavailable or muted voice leaves music playing with written comments',async()=>{for(const available of [false,true]){const f=fixture(available);if(available)f.n.enabled=false;await f.gate.run('start',t(1),intentOf());assert.deepEqual(f.stats(),{playing:true,pauses:0,resumes:0});assert.ok(f.n.text);f.n.dispose();}});
test('manual playback and device changes revoke automatic resume',async()=>{for(const event of ['manual','device']){const f=fixture(),p=f.gate.run('start',t(1),intentOf());await Promise.resolve();if(event==='device')f.setDevice('remote');else f.gate.cancel();f.utterances[0].onend();await p;assert.equal(f.stats().resumes,0);f.n.dispose();}});
test('speech failure falls back to music rather than leaving it paused',async()=>{const f=fixture(),p=f.gate.run('start',t(1),intentOf());await Promise.resolve();f.utterances[0].onerror();await p;assert.equal(f.stats().resumes,1);assert.equal(f.n.voice,null);f.n.dispose();});
test('card introduction finishes before explicit track playback; cancelled introduction never plays',async()=>{for(const cancelled of [false,true]){let finish,played=0;const e=new Engine({queue:()=>({all:[],priority:[]}),save:()=>{},remove:async()=>{},play:async()=>played++,candidates:async()=>[],beforeSessionPlay:()=>new Promise(r=>finish=r)});e.trackChanged(t(1));const p=e.playChoice(t(2),true);while(!finish)await Promise.resolve();assert.equal(played,0);finish(!cancelled);await p;assert.equal(played,cancelled?0:1);assert.equal(e.active,!cancelled);}});
test('muting a live introduction releases only its own pause without cancelling the choice',async()=>{const f=fixture(),p=f.gate.run('start',t(1),intentOf());await Promise.resolve();f.n.toggle();const result=await p;assert.equal(result.cancelled,undefined);assert.equal(f.stats().resumes,1);f.n.dispose();});
test('a replacement comment inherits its own pause and resumes music after the newest speech',async()=>{const f=fixture(),first=f.gate.run('start',t(1),intentOf());await Promise.resolve();const second=f.gate.run('direction',t(1),intentOf());await Promise.resolve();assert.equal((await first).cancelled,true);assert.equal(f.stats().resumes,0);f.utterances[1].onend();await second;assert.equal(f.stats().resumes,1);f.n.dispose();});
