const {chromium}=require('playwright'),{pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:390,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(__dirname,'fixture.html')).href);
  assert.match(await page.locator('.pd h1').innerText(),/3\.3/);assert.equal(await page.evaluate(()=>demo.intervals()),0);assert.match(await page.getByRole('textbox',{name:'¿Qué quieres escuchar?'}).getAttribute('placeholder'),/Yoko/);
  assert.equal(await page.evaluate(()=>PoorDJ.engine.settings.takeover),false);
  const before=await page.evaluate(()=>Spicetify.Player.data.item.uri);
  await page.getByRole('button',{name:'Elegir música conocida',exact:true}).click();assert.equal(await page.locator('[data-choice]').count(),2);
  const first=await page.locator('[data-choice]').evaluateAll(nodes=>nodes.map(n=>n.dataset.choice));
  await page.getByRole('button',{name:'Otra vez',exact:true}).click();const second=await page.locator('[data-choice]').evaluateAll(nodes=>nodes.map(n=>n.dataset.choice));assert.ok(second.every(uri=>!first.includes(uri)));
  assert.equal(await page.evaluate(()=>Spicetify.Player.data.item.uri),before);assert.equal(await page.evaluate(()=>demo.intervals()),0);
  await page.locator('[data-choice]').first().click();await page.waitForFunction(()=>PoorDJ.engine.active && !PoorDJ.engine.busy && !PoorDJ.engine.choiceBusy && PoorDJ.engine.preview.length===1);
  assert.equal(await page.evaluate(()=>demo.intervals()),1);
  await page.locator('#pd-command').fill('solo conocidas y menos comercial');await page.getByRole('button',{name:'Buscar / aplicar',exact:true}).click();await page.waitForFunction(()=>PoorDJ.engine.error);assert.equal(await page.evaluate(()=>PoorDJ.engine.intent.known),true);
  await page.locator('#pd-command').fill('solo conocidas y sin Dillom y más variedad');await page.getByRole('button',{name:'Buscar / aplicar',exact:true}).click();await page.waitForFunction(()=>PoorDJ.engine.intent.variety===80 && !PoorDJ.engine.busy);
  assert.ok((await page.locator('[data-intent]').innerText()).includes('dillom'));
  await page.locator('#pd-command').fill('pon SIN UN PLAN (TEGOCALDERON) de Isma');await page.getByRole('button',{name:'Buscar / aplicar',exact:true}).click();await page.waitForFunction(()=>!PoorDJ.engine.active && !PoorDJ.engine.choiceBusy && Spicetify.Player.data.item.name==='SIN UN PLAN (TEGOCALDERON)');
  assert.equal(await page.evaluate(()=>demo.beforeManualPlay),0);assert.equal(await page.evaluate(()=>demo.intervals()),0);
  assert.equal(await page.evaluate(()=>Spicetify.Queue.nextTracks.filter(t=>t.provider==='context').length),30);
  await page.getByRole('button',{name:'Seguir esta canción',exact:true}).click();await page.waitForFunction(()=>PoorDJ.engine.active && !PoorDJ.engine.busy);assert.equal(await page.evaluate(()=>Spicetify.Player.data.item.name),'SIN UN PLAN (TEGOCALDERON)');await page.evaluate(()=>PoorDJ.engine.stop());
  const searchBefore=await page.evaluate(()=>Spicetify.Player.data.item.uri);await page.locator('#pd-command').fill('Yoko');await page.keyboard.press('Enter');await page.waitForFunction(()=>PoorDJ.engine.commandChoices.length>0);assert.ok(await page.locator('[data-match]').count()>0);assert.equal(await page.evaluate(()=>Spicetify.Player.data.item.uri),searchBefore);await page.locator('[data-match]').first().click();await page.waitForFunction(()=>PoorDJ.engine.active && !PoorDJ.engine.busy && !PoorDJ.engine.choiceBusy);await page.evaluate(()=>PoorDJ.engine.stop());
  await page.locator('#pd-command').fill('Omar Courtz');await page.keyboard.press('Enter');await page.waitForFunction(()=>PoorDJ.engine.commandArtists.length>0);await page.evaluate(()=>{window.testPanel=document.querySelector('.pd');window.testArtist=document.querySelector('[data-mixartist]');});await page.locator('[data-mixartist]').first().click();assert.equal(await page.evaluate(()=>testPanel.isConnected && testArtist.isConnected && document.querySelector('.pd')===testPanel),true);await page.evaluate(()=>PoorDJ.open());assert.equal(await page.locator('#pd-command').inputValue(),'Omar Courtz');assert.equal(await page.evaluate(()=>document.activeElement.dataset.artistmode),'mix');assert.equal(await page.getByRole('button',{name:'Aleatorio',exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'Artista',exact:true}).count(),1);assert.equal(await page.evaluate(()=>PoorDJ.engine.active),false);await page.getByRole('button',{name:'Volver a resultados',exact:true}).click();await page.getByRole('button',{name:'Cerrar resultados',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.pd-choice:visible').count(),0);
  await page.evaluate(()=>PoorDJ.engine.prepareChoices());assert.equal(await page.locator('.pd-choice').first().evaluate(n=>getComputedStyle(n).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.screenshot({path:path.join(__dirname,'../preview.png'),fullPage:true,animations:'disabled'});
  for(let i=0;i<5;i++)await page.evaluate(()=>PoorDJ.open());assert.equal(await page.evaluate(()=>demo.listeners()),3);
  await page.evaluate(()=>PoorDJ.dispose());assert.equal(await page.evaluate(()=>demo.listeners()),0);assert.equal(await page.evaluate(()=>demo.intervals()),0);assert.equal(await page.locator('.pd').count(),0);assert.equal(await page.evaluate(()=>Spicetify.Platform.PlayerAPI.play===demo.originalPlay),true);
  const fresh=await browser.newPage({viewport:{width:700,height:1000}});await fresh.goto(pathToFileURL(path.join(__dirname,'fixture.html')).href+'?fresh');assert.equal(await fresh.evaluate(()=>PoorDJ.engine.exportProfile().schema),3);assert.equal(await fresh.evaluate(()=>PoorDJ.engine.active),false);assert.equal(await fresh.evaluate(()=>demo.intervals()),0);assert.equal(await fresh.evaluate(()=>document.activeElement.id),'pd-command');await fresh.keyboard.press('Tab');assert.equal(await fresh.evaluate(()=>document.activeElement.textContent),'Buscar / aplicar');await fresh.getByRole('button',{name:'Elegir música conocida',exact:true}).click();assert.equal(await fresh.locator('[data-choice]').count(),2);await fresh.locator('[data-choice]').first().focus();await fresh.keyboard.press('Enter');await fresh.waitForFunction(()=>PoorDJ.engine.active && !PoorDJ.engine.busy && !PoorDJ.engine.choiceBusy);await fresh.evaluate(()=>PoorDJ.engine.stop());await fresh.evaluate(()=>PoorDJ.dispose());assert.equal(await fresh.evaluate(()=>demo.listeners()),0);await fresh.close();
  assert.deepEqual(errors,[]);console.log('UI passed: clean initialization, migration, two cards, no mutation while browsing, text filters, Isma precedence, playlist preservation, reduced motion, timers and disposal.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
